### ISSUE TITLE
Generic error about config on startup

### ISSUE THREAD

**Issue by gigatexal** [arianitu/postgres-statefulset#4]
Running on K8s 1.15.2 the master node throws an error about the `PostgreSQL.conf` file and could be related to it thinking that it is reading a directory and not a file.

**Comment by arianitu** [comment]
@gigatexal Can you provide the error?

Sorry didn't see this issue or would have responded earlier.

**Comment by arianitu** [comment]
Closing this, if you still find this to be a problem, do not hesitate to open this again.
