### ISSUE TITLE
error while running "VolumeBinding"

### ISSUE THREAD

**Issue by sante85** [arianitu/postgres-statefulset#6]
error while running "VolumeBinding" filter plugin for pod "postgres-replica-0": pod has unbound immediate PersistentVolumeClaims

**Comment by arianitu** [comment]
@sante85 are you on Azure? Sometimes it takes a little bit for PVCs to bind on certain cloud providers.

**Comment by arianitu** [comment]
@sante85 I'm closing this issue for now since I haven't gotten a response. This error is pretty normal in Kubernetes and resolves its self after the volume mounts.
